### ISSUE TITLE
ForStatement in C has ambiguous AST

### ISSUE THREAD

**Issue by petr-bauch** [codinuum/cca#20]
This might be an intentional choice so feel free to close the issue.
I have noticed that the following codes produce the same AST:
```
for (;cond();) {}
```
and
```
for (;;iter()) {}
```
In the sense that, from the AST itself, it is not possible to determine which expression is the `loop-condition` and which is the `iteration-expression`.

I understand that this might be non-trivial to fix. I noticed that empty `init_statement` in represented as `ExpressionStatement`. Maybe if there was a similar place-holder for an empty(non-present) expression? Or if `ForStatement` had a fixed number of children that may be empty?

**Comment by codinuum** [comment]
I guess you have inspected the ASTs (in XML format) exported by giving `-dump:ast` option.
If so, it is due to lack of information in the exported ASTs.
Internally, each AST has a _position vector_ holding the number of children for each _logical_ position.
For example, `ForStatement` has four logical positions. The vector for the former case is `(0, 1, 0, 1)`, and `(0, 0, 1, 1)` for the latter. The ASTs represented as RDF triples (in N-Triple format) exported by giving `-fact -fact:ast` option have that information, although it may be hard for you to read RDF triples.
We will discuss how to handle this issue...

**Comment by codinuum** [comment]
We have experimentally modified the cpp parser to generate a leaf node for a null condition at `develop` branch.
For `for (;cond();) {}` and `for (;;iter()) {}`, the following trees will be produced respectively.
```
<ForStatement>
  <ExpressionStatement>
  <PostfixExpressionFunCall>
    <Identifier:cond>
  <CompoundStatement>
```
```
<ForStatement>
  <ExpressionStatement>
  <Condition>
  <PostfixExpressionFunCall>
    <Identifier:iter>
  <CompoundStatement>
```

**Comment by petr-bauch** [comment]
Wow. Thank you so much. This looks great.
